language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
env:
  - TEST_SUITE=compile
  - TEST_SUITE=coveralls
  - TEST_SUITE=lint
  - TEST_SUITE=test
script: "npm run-script $TEST_SUITE"
