sudo: false
language: node_js
node_js:
  - 0.10
  - 0.12
  - 4
  - 5
addons:
  firefox: latest
before_script:
  - sh -e /etc/init.d/xvfb start
env:
  global:
    - DISPLAY=:99.0
  matrix:
    - TEST_SUITE=compile
    - TEST_SUITE=test
matrix:
  include:
    - node_js: 4
      env: TEST_SUITE=coveralls
    - node_js: 4
      env: TEST_SUITE=lint
script: npm run-script $TEST_SUITE
